query singleProduct ($id: String!) {
  product(id: $id) {
    sys {
      id
    }
    title
    price
    description {
      json
    }
    image {
      url
    }
  }
}

query allProducts {
  productCollection {
    items {
      sys {
        id
      }
      title
      price
      description {
        json
      }
      image {
        url
      }
    }
  }
}
query productsBySection ($id: String!) {
  productSection (id: $id) {
    productsCollection {
      items {
				sys {
      		id
    		}
    		title
    		price
    		description {
      		json
    		}
    		image {
      		url
    		}
      }
    }
  }
}